site_name: Gay Web Icons
site_url: https://gaywebicons.xyz
site_author: David Gerard
site_description: A collection of icons of gay Websites as a Web font.
site_dir: _site
strict: true
theme:
  name: material
  features:
    - content.code.copy
    - content.code.select
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
