site_name: Gay Web Icons
site_url: https://gaywebicons.xyz
site_author: David Gerard
site_description: A collection of icons of gay Websites as a Web font.
site_dir: _site
strict: false
theme:
  name: material
  features:
    - content.code.copy
    - content.code.select
    - announce.dismiss
    - header.autohide
  palette:
    scheme: slate
    primary: pink
    accent: purple
  logo: assets/icon.png
  favicon: assets/icon.png
  custom_dir: docs/overrides
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
plugins:
  - privacy
  - blog
extra:
  consent:
    actions:
      - accept
      - reject
      - manage
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    cookies:
      analytics:
        name: Google analytics
      github:
        name: GitHub Cookies
extra_css:
  - https://cdn.gaywebicons.xyz/style.css
